# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/redaphid/Projects/Octoblu/arduino-mock

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/redaphid/Projects/Octoblu/arduino-mock

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/redaphid/Projects/Octoblu/arduino-mock/CMakeFiles /home/redaphid/Projects/Octoblu/arduino-mock/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/redaphid/Projects/Octoblu/arduino-mock/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arduino_mock

# Build rule for target.
arduino_mock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arduino_mock
.PHONY : arduino_mock

# fast build rule for target.
arduino_mock/fast:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/build
.PHONY : arduino_mock/fast

src/Arduino.o: src/Arduino.cc.o
.PHONY : src/Arduino.o

# target to build an object file
src/Arduino.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Arduino.cc.o
.PHONY : src/Arduino.cc.o

src/Arduino.i: src/Arduino.cc.i
.PHONY : src/Arduino.i

# target to preprocess a source file
src/Arduino.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Arduino.cc.i
.PHONY : src/Arduino.cc.i

src/Arduino.s: src/Arduino.cc.s
.PHONY : src/Arduino.s

# target to generate assembly for a file
src/Arduino.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Arduino.cc.s
.PHONY : src/Arduino.cc.s

src/ArduinoMockAll.o: src/ArduinoMockAll.cc.o
.PHONY : src/ArduinoMockAll.o

# target to build an object file
src/ArduinoMockAll.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/ArduinoMockAll.cc.o
.PHONY : src/ArduinoMockAll.cc.o

src/ArduinoMockAll.i: src/ArduinoMockAll.cc.i
.PHONY : src/ArduinoMockAll.i

# target to preprocess a source file
src/ArduinoMockAll.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/ArduinoMockAll.cc.i
.PHONY : src/ArduinoMockAll.cc.i

src/ArduinoMockAll.s: src/ArduinoMockAll.cc.s
.PHONY : src/ArduinoMockAll.s

# target to generate assembly for a file
src/ArduinoMockAll.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/ArduinoMockAll.cc.s
.PHONY : src/ArduinoMockAll.cc.s

src/EEPROM.o: src/EEPROM.cc.o
.PHONY : src/EEPROM.o

# target to build an object file
src/EEPROM.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/EEPROM.cc.o
.PHONY : src/EEPROM.cc.o

src/EEPROM.i: src/EEPROM.cc.i
.PHONY : src/EEPROM.i

# target to preprocess a source file
src/EEPROM.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/EEPROM.cc.i
.PHONY : src/EEPROM.cc.i

src/EEPROM.s: src/EEPROM.cc.s
.PHONY : src/EEPROM.s

# target to generate assembly for a file
src/EEPROM.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/EEPROM.cc.s
.PHONY : src/EEPROM.cc.s

src/Serial.o: src/Serial.cc.o
.PHONY : src/Serial.o

# target to build an object file
src/Serial.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Serial.cc.o
.PHONY : src/Serial.cc.o

src/Serial.i: src/Serial.cc.i
.PHONY : src/Serial.i

# target to preprocess a source file
src/Serial.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Serial.cc.i
.PHONY : src/Serial.cc.i

src/Serial.s: src/Serial.cc.s
.PHONY : src/Serial.s

# target to generate assembly for a file
src/Serial.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Serial.cc.s
.PHONY : src/Serial.cc.s

src/Spark.o: src/Spark.cc.o
.PHONY : src/Spark.o

# target to build an object file
src/Spark.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Spark.cc.o
.PHONY : src/Spark.cc.o

src/Spark.i: src/Spark.cc.i
.PHONY : src/Spark.i

# target to preprocess a source file
src/Spark.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Spark.cc.i
.PHONY : src/Spark.cc.i

src/Spark.s: src/Spark.cc.s
.PHONY : src/Spark.s

# target to generate assembly for a file
src/Spark.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Spark.cc.s
.PHONY : src/Spark.cc.s

src/WiFi.o: src/WiFi.cc.o
.PHONY : src/WiFi.o

# target to build an object file
src/WiFi.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/WiFi.cc.o
.PHONY : src/WiFi.cc.o

src/WiFi.i: src/WiFi.cc.i
.PHONY : src/WiFi.i

# target to preprocess a source file
src/WiFi.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/WiFi.cc.i
.PHONY : src/WiFi.cc.i

src/WiFi.s: src/WiFi.cc.s
.PHONY : src/WiFi.s

# target to generate assembly for a file
src/WiFi.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/WiFi.cc.s
.PHONY : src/WiFi.cc.s

src/Wire.o: src/Wire.cc.o
.PHONY : src/Wire.o

# target to build an object file
src/Wire.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Wire.cc.o
.PHONY : src/Wire.cc.o

src/Wire.i: src/Wire.cc.i
.PHONY : src/Wire.i

# target to preprocess a source file
src/Wire.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Wire.cc.i
.PHONY : src/Wire.cc.i

src/Wire.s: src/Wire.cc.s
.PHONY : src/Wire.s

# target to generate assembly for a file
src/Wire.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/Wire.cc.s
.PHONY : src/Wire.cc.s

src/serialHelper.o: src/serialHelper.cc.o
.PHONY : src/serialHelper.o

# target to build an object file
src/serialHelper.cc.o:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/serialHelper.cc.o
.PHONY : src/serialHelper.cc.o

src/serialHelper.i: src/serialHelper.cc.i
.PHONY : src/serialHelper.i

# target to preprocess a source file
src/serialHelper.cc.i:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/serialHelper.cc.i
.PHONY : src/serialHelper.cc.i

src/serialHelper.s: src/serialHelper.cc.s
.PHONY : src/serialHelper.s

# target to generate assembly for a file
src/serialHelper.cc.s:
	$(MAKE) -f CMakeFiles/arduino_mock.dir/build.make CMakeFiles/arduino_mock.dir/src/serialHelper.cc.s
.PHONY : src/serialHelper.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... arduino_mock"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Arduino.o"
	@echo "... src/Arduino.i"
	@echo "... src/Arduino.s"
	@echo "... src/ArduinoMockAll.o"
	@echo "... src/ArduinoMockAll.i"
	@echo "... src/ArduinoMockAll.s"
	@echo "... src/EEPROM.o"
	@echo "... src/EEPROM.i"
	@echo "... src/EEPROM.s"
	@echo "... src/Serial.o"
	@echo "... src/Serial.i"
	@echo "... src/Serial.s"
	@echo "... src/Spark.o"
	@echo "... src/Spark.i"
	@echo "... src/Spark.s"
	@echo "... src/WiFi.o"
	@echo "... src/WiFi.i"
	@echo "... src/WiFi.s"
	@echo "... src/Wire.o"
	@echo "... src/Wire.i"
	@echo "... src/Wire.s"
	@echo "... src/serialHelper.o"
	@echo "... src/serialHelper.i"
	@echo "... src/serialHelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

